### ISSUE TITLE
bump apache-commons-compress from 1.19 to 1.21 in kafka-ui-api

### ISSUE THREAD

**Issue by rgsurfs** [provectus/kafka-ui#1084]
Current version in use is almost two years old.

https://mvnrepository.com/artifact/org.apache.commons/commons-compress

**Comment by Haarolean** [comment]
Hi,

there's nothing wrong with using older versions of dependencies (implying there are no known security vulnerabilities, which is true for 1.19). On the other hand, bumping dependency version may require additional testing overhead, because sometimes even minor bumps can cause some bugs/problems/instabilities.
Considering these facts, I'm closing this since there's no need in bumping this dependency so far.

**Comment by Haarolean** [comment]
Discussed in #1083, that's a transitive dependency.
