### ISSUE TITLE
Documentation for docker run is invalid

### ISSUE THREAD

**Issue by maxifom** [provectus/kafka-ui#151]
It states: `Then access the web UI at http://localhost:9000`

But it should state that the port is 8080. Also need to -p 8080:8080 to be accessible from the host and environment variables need line breaks, otherwise bash cannot read it correctly.

**Comment by alex198710** [comment]
Hello,
I agree that the docker command line is not well-formed. The docker image name should be at the end and no port published.
The doc should be updated with at least:
```
docker run -d \
-e KAFKA_CLUSTERS_0_NAME=local \
-e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=localhost:9092 \
-e KAFKA_CLUSTERS_0_ZOOKEEPER=localhost:2181 \
-p 9000:8080 \
provectuslabs/kafka-ui:latest
```

**Comment by andormarkus** [comment]
Hi @alex198710 @maxifom 

This was fixed in the following commits:
[https://github.com/provectus/kafka-ui/commit/987150c1a5e2e083c44b6cd7c269228e6668f092](url)
[https://github.com/provectus/kafka-ui/commit/1d60db44df81ed0a1c8a935f49bdbe4c7ad4ead6](url)

Docker-compose example:
[https://github.com/provectus/kafka-ui/pull/173](url)

This issue can be closed
