### ISSUE TITLE
Sort by Size/Number of messages

### ISSUE THREAD

**Issue by Tri0L** [provectus/kafka-ui#1512]
### Is your proposal related to a problem?

Sometimes I need to find biggest topic in cluster. It will be great if I can sort list topics by `Size`/`Number of messages` in UI by click on table header like this is working for `Total partitions` or `Out of sync replicas`

**Comment by Haarolean** [comment]
Hi, thanks for the suggestion! We'll take this into consideration :)

**Comment by Haarolean** [comment]
Related: #1383

**Comment by iliax** [comment]
@Tri0L thank you for suggestion. Unfortunately Number of message sorting is not likely to be done, since to calculate number of messages we need to do several heavy API calls. Currently we do it after sorting applied. 
As for size - it is doable, since this data is cached (updated every 30 sec by default).

**Comment by iliax** [comment]
@ValentinPrischepa please take it to account ^
