### ISSUE TITLE
Inconsistency in pagination for topics

### ISSUE THREAD

**Issue by Khakha-A** [provectus/kafka-ui#1523]
**Describe the bug**
(A clear and concise description of what the bug is.)
Pagination automatically jumps to Page 1 even if search was initiated on Page 2 or any other page; makes to navigate to the required page multiple times

**Set up**
(How do you run the app? 
Which version of the app are you running? Provide either docker image version or check commit hash at the top left corner. We won't be able to help you without this information.)
https://www.kafka-ui.provectus.io/ui

**Steps to Reproduce**

1. Go to Topics - Page 2
2. Start search for any of the topics (e.g. asd123)
3. Clear the search field
4. Page 1 is displayed, not Page 2

**Expected behavior**
(A clear and concise description of what you expected to happen)
Page 2 is still displayed when search field info is cleaned.

**Screenshots**
(If applicable, add screenshots to help explain your problem)

**Additional context**
(Add any other context about the problem here)

**Comment by agolosen** [comment]
Always returns to the first page after viewing/editing a topic or schema from the page 2, 3 etc.
  Steps to Reproduce:
1. Go to Topics (Schemas) - Page 2
2. Click a topic(schema) for viewing it (editing)
3. Return to the Topics(Schemas) overview page
4. Page 1 is displayed, not Page 2

Expected behaviour:
Page 2 is still displayed when you returned to the list.
