### ISSUE TITLE
kafka ui can not connect to local kafka cluster

### ISSUE THREAD

**Issue by CharlesJu1** [provectus/kafka-ui#1846]
**Describe the bug**

follow the documentation to run kafka ui, it can not connect to local kafka cluster. Both kakfa ui and kafka cluster are running on a macos, not in docker container.

**Set up**

(base) ~/kafka-ui $ git log
commit b4e52afbdb383c378404905d54fd32f8b2b58617 (HEAD -> master, origin/master, origin/HEAD)
Author: Mgrdich <46796009+Mgrdich@users.noreply.github.com>
Date:   Thu Apr 14 20:24:58 2022 +0400

    Issues/1740 live tailing order (#1824)
    
    * fixing Message addition order during Live tailing
    
    * fixing Message addition order during Live tailing adding tests suites
    
    * minor changes in the function name for prepending addTopics during live mode
    
    * delete minor code repetition
    
    Co-authored-by: Roman Zabaluev <rzabaluev@provectus.com>

**Steps to Reproduce**

1.  start local kafka cluster. 
```
(base) /usr/local/etc/kafka $ /usr/local/opt/kafka/bin/kafka-server-start --version
[2022-04-18 18:06:03,204] INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$)
3.1.0 (Commit:37edeed0777bacb3).
```
2. start kafka ui
```
(base) ~/kafka-ui/kafka-ui-api $ ./mvnw spring-boot:run -Pprod
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.provectus:kafka-ui-api >---------------------
[INFO] Building kafka-ui-api 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:2.6.3:run (default-cli) > test-compile @ kafka-ui-api >>>
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.1:check (checkstyle) @ kafka-ui-api ---
[INFO] You have 0 Checkstyle violations.
[INFO] 
[INFO] --- git-commit-id-plugin:4.0.0:revision (get-the-git-infos) @ kafka-ui-api ---
[INFO] 
[INFO] --- antlr4-maven-plugin:4.7.1:antlr4 (default) @ kafka-ui-api ---
[INFO] No grammars to process
[INFO] ANTLR 4: Processing source directory /Users/cju/kafka-ui/kafka-ui-api/src/main/antlr4
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.0:install-node-and-npm (install node and npm) @ kafka-ui-api ---
[INFO] Node v14.17.1 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.0:npm (npm install) @ kafka-ui-api ---
[INFO] Running 'npm install' in /Users/cju/kafka-ui/kafka-ui-react-app
[INFO] 
[INFO] > kafka-ui@0.1.0 prepare /Users/cju/kafka-ui/kafka-ui-react-app
[INFO] > cd .. && husky install kafka-ui-react-app/.husky
[INFO] 
[INFO] husky - Git hooks installed
[INFO] npm WARN acorn-import-assertions@1.8.0 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.
[INFO] npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
[INFO] npm WARN ts-jest@26.5.6 requires a peer of jest@>=26 <27 but none is installed. You must install peer dependencies yourself.
[INFO] 
[INFO] audited 2315 packages in 7.811s
[INFO] 
[INFO] 227 packages are looking for funding
[INFO]   run `npm fund` for details
[INFO] 
[INFO] found 3 vulnerabilities (1 moderate, 2 high)
[INFO]   run `npm audit fix` to fix them, or `npm audit` for details
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.0:npm (npm run build) @ kafka-ui-api ---
[INFO] Running 'npm run build' in /Users/cju/kafka-ui/kafka-ui-react-app
[INFO] 
[INFO] > kafka-ui@0.1.0 build /Users/cju/kafka-ui/kafka-ui-react-app
[INFO] > react-scripts build
[INFO] 
[INFO] Creating an optimized production build...


[INFO] Compiled successfully.
[INFO] 
[INFO] File sizes after gzip:
[INFO] 
[INFO]   445.99 kB  build/static/js/main.a920c06c.js
[INFO]   34.87 kB   build/static/css/main.bf915e18.css
[INFO] 
[INFO] The project was built assuming it is hosted at ./.
[INFO] You can control this with the homepage field in your package.json.
[INFO] 
[INFO] The build folder is ready to be deployed.
[INFO] 
[INFO] Find out more about deployment here:
[INFO] 
[INFO]   https://cra.link/deployment
[INFO] 
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ kafka-ui-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ kafka-ui-api ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (copy-resources) @ kafka-ui-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 29 resources
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ kafka-ui-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ kafka-ui-api ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< spring-boot-maven-plugin:2.6.3:run (default-cli) < test-compile @ kafka-ui-api <<<
[INFO] 
[INFO] 
[INFO] --- spring-boot-maven-plugin:2.6.3:run (default-cli) @ kafka-ui-api ---
[INFO] Attaching agents: []
 _   _ ___    __             _                _          _  __      __ _
| | | |_ _|  / _|___ _ _    /_\  _ __ __ _ __| |_  ___  | |/ /__ _ / _| |_____
| |_| || |  |  _/ _ | '_|  / _ \| '_ / _` / _| ' \/ -_) | ' </ _` |  _| / / _`|
 \___/|___| |_| \___|_|   /_/ \_| .__\__,_\__|_||_\___| |_|\_\__,_|_| |_\_\__,|
                                 |_|                                             

2022-04-18 18:09:03,391 INFO  [background-preinit] o.h.v.i.u.Version: HV000001: Hibernate Validator 6.2.0.Final
2022-04-18 18:09:03,403 INFO  [main] c.p.k.u.KafkaUiApplication: Starting KafkaUiApplication using Java 17.0.2 on Charless-MacBook-Pro-3.local with PID 14961 (/Users/cju/kafka-ui/kafka-ui-api/target/classes started by cju in /Users/cju/kafka-ui/kafka-ui-api)
2022-04-18 18:09:03,403 DEBUG [main] c.p.k.u.KafkaUiApplication: Running with Spring Boot v2.6.3, Spring v5.3.15
2022-04-18 18:09:03,403 INFO  [main] c.p.k.u.KafkaUiApplication: No active profile set, falling back to default profiles: default
2022-04-18 18:09:04,308 INFO  [main] o.s.d.r.c.RepositoryConfigurationDelegate: Bootstrapping Spring Data LDAP repositories in DEFAULT mode.
2022-04-18 18:09:04,350 INFO  [main] o.s.d.r.c.RepositoryConfigurationDelegate: Finished Spring Data repository scanning in 37 ms. Found 0 LDAP repository interfaces.
2022-04-18 18:09:05,355 INFO  [main] o.s.b.a.e.w.EndpointLinksResolver: Exposing 2 endpoint(s) beneath base path '/actuator'
2022-04-18 18:09:05,468 INFO  [main] o.s.b.a.s.r.ReactiveUserDetailsServiceAutoConfiguration: 

Using generated security password: 9b507c0c-51da-4d12-b9ca-24b9404aa6c8

2022-04-18 18:09:05,544 WARN  [main] c.p.k.u.c.a.DisabledAuthSecurityConfig: Authentication is disabled. Access will be unrestricted.
2022-04-18 18:09:05,649 INFO  [main] o.s.l.c.s.AbstractContextSource: Property 'userDn' not set - anonymous context will be used for read-write operations
2022-04-18 18:09:05,864 INFO  [main] o.s.b.w.e.n.NettyWebServer: Netty started on port 8080
2022-04-18 18:09:05,877 INFO  [main] c.p.k.u.KafkaUiApplication: Started KafkaUiApplication in 3.126 seconds (JVM running for 3.522)
```

**Expected behavior**

Kafka UI should show the local kafka cluster. But it does not.

**Screenshots**

<img width="1302" alt="Screen Shot 2022-04-18 at 6 12 12 PM" src="https://user-images.githubusercontent.com/1816882/163794007-4c3f87f5-b96f-4bc9-a0a0-68fb0051a67e.png">

**Additional context**

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. Have you edit the app config? `application.yml` in your case.

**Comment by CharlesJu1** [comment]
> 



> Hey, thanks for reaching out. Have you edit the app config? `application.yml` in your case.

No. I did not edit any of the config files in the src/main/resources folder.

**Comment by Haarolean** [comment]
You have to either specify your external config path location or edit the once in resources. You have to specify bootstrapServers and other properties to reach your kafka clusters.

**Comment by CharlesJu1** [comment]
> You have to either specify your external config path location or edit the once in resources. You have to specify bootstrapServers and other properties to reach your kafka clusters.
I copied the content from application-local.yml to application.yml and it worked. Thanks.

**Comment by Haarolean** [comment]
Glad it works!

**Comment by Thilaknath** [comment]
@CharlesJu1 Do you mind sharing your config in application.yaml?

**Comment by Haarolean** [comment]
@Thilaknath basically there are still all the same env variables (see bottom of the README file) but each underscore symbol is a new indentation line in yaml.
An [example](https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/resources/application-local.yml)

**Comment by adrian-moisa** [comment]
I've wasted a lot of time trying to get Kafka-GUI running. Thanks to the tutorial bellow now I understand properly how to setup a podman bridge network and how to configure advertised listeners in kafka. I'll list all the docker commands I've used to get a local one node setup running. Note: podman or docker, the commands are the same. Both kafka and kafka-ui are in containers. If you read the tutorial carefully you'll see this matters a lot. If you then want to connect from local app to container kafka you'll need extra settings.

- [My Python/Java/Spring/Go/Whatever Client Won’t Connect to My Apache Kafka Cluster in Docker/AWS/My Brother’s Laptop. Please Help!](https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/) - Contains a deep review of all potential issues when the kafka cluster fails to start. Thanks to this tutorial I managed to get Kafka UI running. The key was to setup a podman network and to properly name all containers. Once the containers are named we can used these names in the connection strings params when starting kafka-gui. Note: most tutorials prefer to name the kafka container `broker`. I used `kafka` for extra clarity, do as you please in your case.

- [My Python/Java/Spring/Go/Whatever Client Won’t Connect to My Apache Kafka Cluster in Docker/AWS/My Brother’s Laptop. Please Help!](https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/) - Contains a deep review of all potential issues when the kafka cluster fails to start. Thanks to this tutorial I managed to get Kafka UI running. The key was to setup a podman network and to properly name all containers. Once the containers are named we can used these names in the connection strings params when starting kafka-gui.

**Download Kafka & Zookeeper**
- `podman pull bitnami/kafka` - Download kafka
- `podman pull zookeeper` - Download Zookeeper

**Kafka Network**
- `podman network create vs_kafka`

**Zookeeper Volumes**
Needed to persist data (also perf reasons explained in zookeeper.md). Notice that we are creating volumes for `zookeeper`. In production we will have more instances.
- `podman volume create zookeeper-dataDir` - `/dataDir` - Snapshot of the in-memory database, current state of the data tree and the content of ephemeral nodes
- `podman volume create zookeeper-dataLogDir` - `/dataLogDir` - Sequential record of all changes made to the ZooKeeper data tree since the last snapshot
- `podman volume create zookeeper-logs` - `/logs` - Server logs, error logs, or diagnostic logs

**Kafka Volume**
- `podman volume create kafka-data` - By mounting a Docker volume to Kafka, the data generated and stored by Kafka will persist even if the container is stopped or removed.

**Run Zookeeper** 
Note: we are running zookeeper outside of the mock-api-pod. We will have more pods all connected to the same kafka server. This setup will be improved in production to ensure scalability and resilience.
```
podman run -dt --name zookeeper \
--network=vs_kafka \
-p 2181:2181 \
-e ZOOKEEPER_CLIENT_PORT=2181 \
-v 'zookeeper-dataDir:/data:Z' \
-v 'zookeeper-dataLogDir:/datalog:Z' \
-v 'zookeeper-logs:/logs:Z' \
docker.io/library/zookeeper
```

**Run Kafka** (confluentinc/cp-kafka)
Note: we are running zookeeper outside of the mock-api-pod.
Warning! `ALLOW_PLAINTEXT_LISTENER=yes` is for development env, not production.

```
podman run -dt --name kafka \
--network=vs_kafka \
-p 7203:7203 \
-p 9092:9092 \
-v kafka-data:/kafka/data \
-e KAFKA_BROKER_ID=1 \
-e ALLOW_PLAINTEXT_LISTENER=yes \
-e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
-e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 \
-e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
docker.io/bitnami/kafka
```

**Create Topic**
This instruction can be defined in docker-compose or k8 yaml as an init instruction. For now (May 2023) we have to manually configure it. 
Reminder: https://stackoverflow.com/questions/64865361/docker-compose-create-kafka-topics
- `podman exec -it kafka sh` - Connect to kafka container
- `cd /opt/bitnami/kafka/bin`- Cd to bins of kafka
- `kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic api-mock` - Create a new topic
- `kafka-configs.sh --bootstrap-server localhost:9092 --entity-type brokers --entity-name 1 --describe ` - If you want to double check on the settings. Optional, no need to run this unless you are debugging

**Kafka GUI**
Warning, starting kafka ui with this command does not create a password. In prod this needs to be auth.
- `podman pull provectuslabs/kafka-ui` - Get the image
- `cd to /visual-space` - We need to cd here so that the volume param works regardless of where you host your projects
- Start kafka UI on port 9090 to avoid collisions with the running `api-mocks`.
```
podman run -it --name kafka-ui \
--network=vs_kafka \
-p 9090:8080 \
-e KAFKA_CLUSTERS_0_NAME=local \
-e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 \
-e KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181 \
-e KAFKA_BROKERCONNECT=kafka:9092 \
-e DYNAMIC_CONFIG_ENABLED=true \
provectuslabs/kafka-ui
``` 
- `http://localhost:9090/` - Visit the link to use the web gui for kafka
