### ISSUE TITLE
Mutliple users creation

### ISSUE THREAD

**Issue by Lokeshmaxi** [provectus/kafka-ui#2195]
I have deployed Kafka-UI using helm chart,kindly help us to create multiple users in Kafka-UI

**Comment by Haarolean** [comment]
Hey, thanks for reaching out.

We do not support multiple users with basic (login form) auth. 
In order to get one, you can use either [oauth2](https://github.com/provectus/kafka-ui/wiki/Set-up-OAuth2---SSO) or [ldap](https://github.com/provectus/kafka-ui/wiki/FAQ#ldap).

Also, we're planning to implement role based access control (#753) within current release.

Feel free to ask any other questions if you get any, either here or on our discord.
