### ISSUE TITLE
Why I'm getting Broker may not be available error?

### ISSUE THREAD

**Issue by gosforth** [provectus/kafka-ui#2349]
In server.properties config I have lines:

```
listeners=PLAINTEXT://127.0.0.1:9092
advertised.listeners=PLAINTEXT://127.0.0.1:9092
```

Zookeeper is running, Kafka is running. I can create topic with:

kafka-topics.bat --create --topic quickstart-events --bootstrap-server localhost:9092

I want to run Kafka-ui. So, I run docker desktop container:

```
docker run -p 8080:8080 \
	-e KAFKA_CLUSTERS_0_NAME=local \
	-e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=127.0.0.1:9092 \
	-d provectuslabs/kafka-ui:latest 
```

But there's no connection and I'm getting error:
```
o.a.k.c.NetworkClient: [AdminClient clientId=adminclient-2] Connection to node -1 (/127.0.0.1:9092) could not be established. Broker may not be available.
```

What can be wrong?
Regards

**Comment by Haarolean** [comment]
Hi,

a "localhost" in `KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS` property points at *container's* localhost, not your host machine one.

Here's [a guide](https://github.com/provectus/kafka-ui/discussions/1081) how to access kafka on your host machine.
Let me know if you have any other problems, or feel free to hop into our discord.

**Comment by gosforth** [comment]
Sorry, I do not get it. In the post you mention the solution is what I did: IP address of host where Kafka or Docker is (same in my scenario). But this is not working for me.

**Comment by gosforth** [comment]
OK, I've changed to:

`docker run -p 8080:8080 -e KAFKA_CLUSTERS_0_NAME=local -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=host.docker.internal:9092 -d provectuslabs/kafka-ui:latest`

I ping host.docker.internal and I get reply.
In config I have:

```
listeners=PLAINTEXT://192.168.1.145:9092
advertised.listeners=PLAINTEXT://192.168.1.145:9092
```

Tried as well 'localhost' and '127.0.0.1' - does not work

**Comment by gosforth** [comment]
Now:
2022-07-27 19:52:01,011 DEBUG [parallel-1] c.p.k.u.s.ClustersMetricsScheduler: Start getting metrics for kafkaCluster: local
2022-07-27 19:52:01,029 ERROR [parallel-1] c.p.k.u.s.MetricsService: Failed to collect cluster local info

**Comment by Haarolean** [comment]
@gosforth ping me on discord so we can take a look together

**Comment by shaarif-khan** [comment]
has it been resolved, facing the same issue

**Comment by Haarolean** [comment]
> has it been resolved, facing the same issue

Hi, please open up a new issue and follow the template: we need the version, configs, etc.

**Comment by adrian-moisa** [comment]
I've wasted a lot of time trying to get Kafka-GUI running. Thanks to the tutorial bellow now I understand properly how to setup a podman bridge network and how to configure advertised listeners in kafka. I'll list all the docker commands I've used to get a local one node setup running. Note: podman or docker, the commands are the same. Both kafka and kafka-ui are in containers. If you read the tutorial carefully you'll see this matters a lot. If you then want to connect from local app to container kafka you'll need extra settings.

- [My Python/Java/Spring/Go/Whatever Client Won’t Connect to My Apache Kafka Cluster in Docker/AWS/My Brother’s Laptop. Please Help!](https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/) - Contains a deep review of all potential issues when the kafka cluster fails to start. Thanks to this tutorial I managed to get Kafka UI running. The key was to setup a podman network and to properly name all containers. Once the containers are named we can used these names in the connection strings params when starting kafka-gui. Note: most tutorials prefer to name the kafka container `broker`. I used `kafka` for extra clarity, do as you please in your case.

**Download Kafka & Zookeeper**
- `podman pull bitnami/kafka` - Download kafka
- `podman pull zookeeper` - Download Zookeeper

**Kafka Network**
- `podman network create kafka-bridge` - Name it as you please

**Zookeeper Volumes**
Needed to persist data. Notice that we are creating volumes for one `zookeeper` instance. In production we will have more instances.
- `podman volume create zookeeper-dataDir` - `/dataDir` - Snapshot of the in-memory database, current state of the data tree and the content of ephemeral nodes
- `podman volume create zookeeper-dataLogDir` - `/dataLogDir` - Sequential record of all changes made to the ZooKeeper data tree since the last snapshot
- `podman volume create zookeeper-logs` - `/logs` - Server logs, error logs, or diagnostic logs

**Kafka Volume**
- `podman volume create kafka-data` - By mounting a Docker volume to Kafka, the data generated and stored by Kafka will persist even if the container is stopped or removed.

**Run Zookeeper** 
Note: we are running zookeeper outside of the any api pods that are defined. We will have more pods all connected to the same kafka server. This one node setup needs to be improved in production to ensure scalability and resilience.
```
podman run -dt --name zookeeper \
--network=kafka-bridge \
-p 2181:2181 \
-e ZOOKEEPER_CLIENT_PORT=2181 \
-v 'zookeeper-dataDir:/data:Z' \
-v 'zookeeper-dataLogDir:/datalog:Z' \
-v 'zookeeper-logs:/logs:Z' \
docker.io/library/zookeeper
```

**Run Kafka**
Note: we are running zookeeper outside of the mock-api-pod.
Warning! `ALLOW_PLAINTEXT_LISTENER=yes` is for development env, not production.

```
podman run -dt --name kafka \
--network=kafka-bridge \
-p 7203:7203 \
-p 9092:9092 \
-v kafka-data:/kafka/data \
-e KAFKA_BROKER_ID=1 \
-e ALLOW_PLAINTEXT_LISTENER=yes \
-e KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181 \
-e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092 \
-e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
docker.io/bitnami/kafka
```

**Create Topic**
This instruction can be defined in docker-compose or k8 yaml as an init instruction. For now (May 2023) we will manually configure it. [Docker compose create kafka topics](https://stackoverflow.com/questions/64865361/docker-compose-create-kafka-topics).
- `podman exec -it kafka sh` - Connect to kafka container
- `cd /opt/bitnami/kafka/bin`- Cd to bins of kafka
- `kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic api-mock` - Create a new topic
- `kafka-configs.sh --bootstrap-server localhost:9092 --entity-type brokers --entity-name 1 --describe ` - If you want to double check on the settings. Optional, no need to run this unless you are debugging

**Kafka GUI**
Warning, starting kafka ui with this command does not create a password. In prod this needs to be auth.
- `podman pull provectuslabs/kafka-ui` - Get the image
- Start kafka UI on port 9090 to avoid collisions with anything running on 8080.
```
podman run -it --name kafka-ui \
--network=kafka-bridge \
-p 9090:8080 \
-e KAFKA_CLUSTERS_0_NAME=local \
-e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092 \
-e KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181 \
-e KAFKA_BROKERCONNECT=kafka:9092 \
-e DYNAMIC_CONFIG_ENABLED=true \
provectuslabs/kafka-ui
``` 
- `http://localhost:9090/` - Visit the link to use the web gui for kafka

**Connecting to Kafka container CLI**
- `podman exec -it kafka sh` - Connect to kafka container
- `cd /opt/bitnami/kafka/bin`- Cd to bins of kafka
- `kafka-topics.sh --bootstrap-server=localhost:9092 --list` - List all topics

**Inspecting Kafka via local CLI**
- `brew install kcat` - First install kafkacat (renamed to kcat)
- `kcat -b localhost:9092 -L` - List the available topics in the Kafka cluster

<img width="1044" alt="image" src="https://github.com/provectus/kafka-ui/assets/11160141/ac293d65-baba-4039-9158-4a71dfcbe678">

**Comment by Haarolean** [comment]
@adrian-moisa podman supports running docker-compose files and we have a lot of examples [available](https://github.com/provectus/kafka-ui/tree/master/documentation/compose)

**Comment by adrian-moisa** [comment]
Thanks for the reply @Haarolean. I know about docker compose. I've been using commands in an effort to better understand the operating principles of each single command and step. When toying with docker compose it's a bit harder to have a solid understanding of each step and it's faults. By running command by command I often have the chance to debug stuff that is stuck at a certain step. In the end the entire podman cluster can be exporte to a kubernetes file and reimported in podman or in kubernetes. So basically I don't really see the need in my case for compose.
