### ISSUE TITLE
Latest Ingress changes breaks compatibility with GKE clusters versions (GKE use -gke.XXXX as suffix for version)

### ISSUE THREAD

**Issue by sgolod** [provectus/kafka-ui#2382]
This changes breaks compatibility with GKE clusters versions (GKE use -gke.XXXX as suffix for version).
It can be solved when use semver comparision to full version ("1.19" -> "1.19.0-0")
```
(trimPrefix "v" .Capabilities.KubeVersion.Version | semverCompare ">= 1.19" ) =>
(trimPrefix "v" .Capabilities.KubeVersion.Version | semverCompare ">= 1.19.0-0" )
```

_Originally posted by @sgolod in https://github.com/provectus/kafka-ui/issues/2318#issuecomment-1203893817_

**Comment by Haarolean** [comment]
Hey, thanks for reporting. We'll take a look.

**Comment by azatsafin** [comment]
Hello @sgolod , thx for discovering & reporting this
could you please try to use helm chart from this [branch](https://github.com/provectus/kafka-ui/tree/issues/2382) 
I don't have any GKE available to make final tests.

**Comment by sgolod** [comment]
> 

You forgot to make same changes below (line 35 in this branch).
IMHO, but this patch is overcomplication. This can be done more elegantly by comparing with "1.19.0-0", this solution suggested in same original Helm issue:
https://github.com/helm/helm/issues/3810

**Comment by azatsafin** [comment]
Hi @sgolod 
you comment about line 35 correct, I also found and made correction in my last PR
The line `1.19.0` will be automatically treated as `1.19.0-0[]` when converting to the full semver format. I agree that your proposal will work as well. I Prefer to use my version, because it could be corner case when some K8s produce specific version value which could not be comparaible just with `1.19.0-0`.
