### ISSUE TITLE
Fix backend tests stability on m1/arm

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2449]
Backend tests on m1 work way too bad

**Comment by Haarolean** [comment]
I suggest we expand the scope of this issue: I think we might need arm images for backend tests as well.
We've already got some logic to choose arm images over x86 depending on the architecture (com.provectus.kafka.ui.base.BaseTest#isARM64).

**Comment by Haarolean** [comment]
> I suggest we expand the scope of this issue: I think we might need arm images for backend tests as well. We've already got some logic to choose arm images over x86 depending on the architecture (com.provectus.kafka.ui.base.BaseTest#isARM64).

@shubhwip wanna give it a try? :)

**Comment by shubhwip** [comment]
Sure @Haarolean

**Comment by shubhwip** [comment]
I ran the e2e tests locally and one of the tests failed was `UpdateAvroSchema` in `kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java`
Here are the screenshots
<img width="1440" alt="Screenshot 2022-09-04 at 1 19 44 PM" src="https://user-images.githubusercontent.com/23444368/188303245-6f68574f-0750-49e5-80bd-f75f1f13a1c9.png">

![1662271406945 0](https://user-images.githubusercontent.com/23444368/188303130-c4044675-104c-477a-9a3c-b4d54d64a187.png)

Errors on schema registry side
```
io.confluent.kafka.schemaregistry.rest.exceptions.RestIncompatibleSchemaException: Schema being registered is incompatible with an earlier schema for subject "ab"
	at io.confluent.kafka.schemaregistry.rest.exceptions.Errors.incompatibleSchemaException(Errors.java:133)
```
The reason why it is failing because during update we are changing a top level property and we have created this schema with backward compatibility. Although in our test we are switching to compatibility to None but that didn't have any effect because compatibility is set to `backward_compatible` globally. So in order for this test to work we need to keep top level property same i.e. `name`.

**Comment by Haarolean** [comment]
> I ran the e2e tests locally and one of the tests failed was `UpdateAvroSchema` in `kafka-ui-e2e-checks/src/test/java/com/provectus/kafka/ui/tests/SchemasTests.java` Here are the screenshots <img alt="Screenshot 2022-09-04 at 1 19 44 PM" width="1440" src="https://user-images.githubusercontent.com/23444368/188303245-6f68574f-0750-49e5-80bd-f75f1f13a1c9.png">
> 
> ![1662271406945 0](https://user-images.githubusercontent.com/23444368/188303130-c4044675-104c-477a-9a3c-b4d54d64a187.png)
> 
> Errors on schema registry side
> 
> ```
> io.confluent.kafka.schemaregistry.rest.exceptions.RestIncompatibleSchemaException: Schema being registered is incompatible with an earlier schema for subject "ab"
> 	at io.confluent.kafka.schemaregistry.rest.exceptions.Errors.incompatibleSchemaException(Errors.java:133)
> ```
> 
> The reason why it is failing because during update we are changing a top level property and we have created this schema with backward compatibility. Although in our test we are switching to compatibility to None but that didn't have any effect because compatibility is set to `backward_compatible` globally. So in order for this test to work we need to keep top level property same i.e. `name`.
> 
> Then again I don't get why e2e test passes on some PRs :) ?

@shubhwip thanks for the note, I suppose we can discuss this issue with that test with our QA folks. You can ignore it failing locally for now.
@provectus/kafka-qa @VladSenyuta fyi

**Comment by VladSenyuta** [comment]
@ArthurNiedial FYI

**Comment by Haarolean** [comment]
Currently tests do seem to work fine with replacing `CONFLUENT_PLATFORM_VERSION` in `AbstractIntegrationTest` to `7.2.1.arm64`.
