### ISSUE TITLE
Invalid value for "delete.retention.ms" results in Kafka Broker crash

### ISSUE THREAD

**Issue by ChSchott** [provectus/kafka-ui#2501]
### Entering an invalid value for the "delete.retention.ms" parameter causes the Kafka Broker to crash.

Log from the Kafka Broker:
`org.apache.kafka.common.config.ConfigException: Invalid value -1 for configuration delete.retention.ms: Value must be at least 0`

**Comment by Haarolean** [comment]
Hey, thanks for reaching out. We'll take a look.

**Comment by shubhwip** [comment]
@Haarolean Can you please assign this to me ?

**Comment by shubhwip** [comment]
@ChSchott How did you specify `"delete.retention.ms"` property ? through `kafka-ui` application or other ways ?
Can you specify steps for reproducing the issue ?

**Comment by shubhwip** [comment]
@Haarolean If you have an idea how this could be reproduced. Please comment so that i can look into it further.

**Comment by Haarolean** [comment]
@ChSchott there is a bold and certain reason why we do have issue templates set in place. The one for a bug report (which you used it seems but decided not to follow one) contains an important block named "Steps to Reproduce". Please provide the steps.

**Comment by shubhwip** [comment]
> @ChSchott cool, thanks. @shubhwip kraft mode part might be important here. Still interested to take a look?

Yeah Sure :)

**Comment by shubhwip** [comment]
Thanks @ChSchott. 

@Haarolean Reproduced this problem. basically as per `kafka` documentation, -1 is invalid value for `delete.retention.ms` so this invalid value is not handled properly on kafka side thus resulting in broker crash.
https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#topicconfigs_delete.retention.ms

We can have below ways to deal with this problem.
- Users should be aware about all these properties by seeking kafka confluent documentation
- we can show valid values next to each custom parameters to make sure users are informed and aware before providing values.
- Enforce valid values for each type of custom parameters in `kafka-ui` to avoid any invalid values. Currently we’d generalised same input type for all types of custom parameters. But if we want to enforce this then we need to have different types of input for different params. For e.g. property `[compression.type]`(https://docs.confluent.io/platform/current/installation/configuration/topic-configs.html#topicconfigs_compression.type) has following valid values [uncompressed, zstd, lz4, snappy, gzip, producer] so a dropdown would be required so that end user won’t be able to do any mistake. Other property for e.g. [delete.retention.ms] would require input type number with min and max values as set.

**Comment by Haarolean** [comment]
> @Haarolean Did you get a chance to look at my above comment :) ?

Yeaah I did, just left it without an answer.

Let's leave it as is for now, other options are too much work and not ideal.
