### ISSUE TITLE
Fix broker names' links colors

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2510]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/1494347/187881544-1b934c62-f757-42f4-ac63-2c5214562a02.png">
these are links, should be visible

Also, let's append "Broker" before the broker number

**Comment by MichaelGonzalezMurillo** [comment]
All Links seems to be the same, we can fix that within another issue. Due to clickable row there is no benefit of having an appended "broker" since that is not the real ID that could add confusion. I would remove the "broker" append in the broker details page since that is not following other pages logic as Topics, consumers, schema registry etc.

![Screen Shot 2022-09-07 at 5 18 28 PM](https://user-images.githubusercontent.com/110129349/188999631-05a69249-e3eb-49f3-a7a1-4d5741bca579.png)
![Screen Shot 2022-09-07 at 5 18 15 PM](https://user-images.githubusercontent.com/110129349/188999636-d318204c-5948-425d-b8ac-5bd815ccfe9a.png)
![Screen Shot 2022-09-07 at 5 18 04 PM](https://user-images.githubusercontent.com/110129349/188999638-64bf6965-d2eb-4d47-bfe5-c546623b4e77.png)

Just Brokers details is Adding "Broker" to the name. So that page is not standard.

@Haarolean

**Comment by Haarolean** [comment]
Let's keep it as is. Just a number is too short, visually current variant looks better.
