### ISSUE TITLE
Handle 404/403s on FE

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#2957]

**Comment by Mgrdich** [comment]
Basically Because we use `useQuery` with `suspense` , it will throw an error -> by React Error throwing boundaries and it will propagte to the closest one.

Since in most components we don't have this feature , either we have to close the error throwing propagation, or handle them with Setting Error boundaries ,which i am not sure it the correct way to go.

**Comment by Mgrdich** [comment]
So Since some of the pages are written with redux while other are written with query, two the 404 are handled on two different levels

how to migrate the component from redux to query.
* First transform the request logic.
* then wrap that component with `SuspenseQueryComponent`
* delete isRejected case from them.
