### ISSUE TITLE
Fields previews: make the paths work as json paths

### ISSUE THREAD

**Issue by Haarolean** [provectus/kafka-ui#3013]
currently they work without `$`

**Comment by Mgrdich** [comment]
The problem is not only with the `$` , any bit complex jsonPath does not work with it , cause it uses `Lodash` `get` method, instead of an actually JsonPath identifier, hence other stuff will fail as well.

Example `reddit-comments-avro` from topics messages check the `$.map.array[1:2]`, `map.array[1:2]` stuff like this will not work cause lodash does not support it.

Expressions such as

* `[?(expression)]`
* `[-n:]`


Method will itself will return  undefined over that particular JSON hence the bug.



<br class="Apple-interchange-newline">

**Comment by BulatKha** [comment]
@armenuikafka please double-check the test case has it.

**Comment by armenuikafka** [comment]
> @armenuikafka please double-check the test case has this case.

 separate test case for this issue - https://app.qase.io/case/KAFKAUI-270
