### ISSUE TITLE
Connecting to local cluster - IPv6

### ISSUE THREAD

**Issue by rmpt** [provectus/kafka-ui#3233]
Hi,
I'm starting kafka-ui with docker, the command I'm using is the following:
```
docker run -p 8080:8080
    -e KAFKA_CLUSTERS_0_NAME=kafka-course
    -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=[::1]:9092
    -d provectuslabs/kafka-ui:latest
```

The UI appears ok, but the cluster is always shown as offline.
![image](https://user-images.githubusercontent.com/16465379/212341952-e3d6657f-9714-48a0-a9c5-d34ca7669200.png)

If I click in broker or topic section, it freezes and die. I've alreay tried with localhost:9092 (IPv4), no luck. Am I missing some configuration?

I get an error:
`UnsupportedAddressTypeException: null`

**Comment by Haarolean** [comment]
Hi,

containers are isolated from the host machine, including networking, that's by design.
Neither IPv4 nor IPv6 localhost won't work in this case, unless `host` network mode is used or `host.docker.internal` hack.

Please refer to [this](https://github.com/provectus/kafka-ui/discussions/1081) thread.

**Comment by Haarolean** [comment]
host.docker.internal might not work, depends on your host OS.
`host` network mode is an alternative option.
