### ISSUE TITLE
Backend returns incorrect http statuses

### ISSUE THREAD

**Issue by workshur** [provectus/kafka-ui#331]
Some Create/Update requests returns unpredictable responses:

1. When I try to create schema dup
```
curl 'http://localhost:3000/api/clusters/secondLocal/schemas' \
  -H 'Connection: keep-alive' \
  -H 'sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"' \
  -H 'DNT: 1' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Accept: */*' \
  -H 'Origin: http://localhost:3000' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:3000/ui/clusters/secondLocal/schemas/new' \
  -H 'Accept-Language: en-US,en;q=0.9,ru;q=0.8' \
  --data-raw '{"subject":"my.new","schema":"my.new","schemaType":"AVRO"}' \
  --compressed
  ```
it returns HTTP/1.1 500 Internal Server Error with:
```
{"code":5000,"message":"500 Internal Server Error from POST http://schemaregistry0:8085/subjects/my.new","timestamp":1617110665799,"requestId":"adb03f44","fieldsErrors":null}
```
instead of 409

2. Schema Update should return list of invalid fields in 422 response
3. Topic create dup request returns correct message with incorrect code
```
{"code":5000,"message":"Topic '123' already exists.","timestamp":1617110943045,"requestId":"71474ae8","fieldsErrors":null}
```

Please update All existing api endpoints to return correct responses in format of ErrorResponse

**Comment by Haarolean** [comment]
1. Unfortunately this is the http code from the schema registry itself. It's 500 instead of 409 if you send an invalid request, like this:
`{"subject":"test","schema":"test","schemaType":"AVRO"}`
instead of this:
`{"subject":"test","schemaType":"AVRO","schema":"{\"type\": \"string\"}"}`
It produces 409 if the request body is correct.

2. Seems like it's impossible since schema registry does not forward a list of such fields, but we'll forward an error message from schema registry instead.
```
{
  "code": 4006,
  "message": "Either the input schema or one its references is invalid", // <-- this has changed
  "timestamp": 1626784717378,
  "requestId": "73e2c259",
  "fieldsErrors": null
}
```

3.
