### ISSUE TITLE
Jar creation failed 

### ISSUE THREAD

**Issue by hussam770** [provectus/kafka-ui#3484]
when executing the maven command 

mvn -f kafka-ui-api/pom.xml clean install -Pprod -DskipTests
im getting the below error 

[INFO] ✓ 3 modules transformed.
[INFO] [vite]: Rollup failed to resolve import "components/App" from "C:/Users/hlibd/IdeaProjects/kafka-ui/kafka-ui-react-app/src/index.tsx".
[INFO] This is most likely unintended because it can break your application at runtime.
[INFO] If you do want to externalize this module explicitly add it to
[INFO] `build.rollupOptions.external`
[INFO] error during build:
[INFO] Error: [vite]: Rollup failed to resolve import "components/App" from "C:/Users/hlibd/IdeaProjects/kafka-ui/kafka-ui-react-app/src/index.tsx".
[INFO] This is most likely unintended because it can break your application at runtime.
[INFO] If you do want to externalize this module explicitly add it to

but if if I changed the command to 

mvn -f kafka-ui-api/pom.xml clean install -Pprod -DskipUIBuild=false -DskipTests

it working but the docker container (kafka-ui) is not running successfully due to missing UI artifacts (index.*)

Appreciate your support on this

**Comment by iliax** [comment]
Hello @hussam770 ,
1. what is the working directory from where you running build command? 
2. please try to `cd` to the root kafka-ui directory and run build command from there? (no need to specify pom location in this case)

**Comment by Haarolean** [comment]
Hi, we had some issues with building on windows besides this one(#1582). 

The thing is, right as @iliax suggested, you're running the build in the wrong directory (with the wrong pom file in your case). Try running clean install within the root directory and with the root pom.

**Comment by kunzef** [comment]
Hi, im getting the same error trying to run` ./mvnw clean install -Pprod` as described in the docs. Im trying to build on Windows 10. Im running the command in the root directory. See below my error messages.

[INFO] 
[INFO] ---------------------< com.provectus:kafka-ui-api >---------------------
[INFO] Building kafka-ui-api 0.0.1-SNAPSHOT                               [4/5]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.2.0:clean (default-clean) @ kafka-ui-api ---
[INFO] Deleting C:\Users\Franz\Programming\kafka-ui-api\target
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.2:check (checkstyle) @ kafka-ui-api ---
[INFO] You have 0 Checkstyle violations.
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.8:prepare-agent (prepare-agent) @ kafka-ui-api ---
[INFO] argLine set to -javaagent:C:\\Users\\Franz\\.m2\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.8\\org.jacoco.agent-0.8.8-runtime.jar=destfile=C:\\Users\\Franz\\Programming\\kafka-ui-api\\target\\jacoco.exec
[INFO] 
[INFO] --- git-commit-id-plugin:4.0.0:revision (get-the-git-infos) @ kafka-ui-api ---
[INFO] 
[INFO] --- antlr4-maven-plugin:4.12.0:antlr4 (default) @ kafka-ui-api ---
[INFO] ANTLR 4: Processing source directory C:\Users\Franz\Programming\kafka-ui-api\src\main\antlr4
[INFO] Processing grammar: ksql\KsqlGrammar.g4
[INFO] 
[INFO] --- spring-boot-maven-plugin:3.0.5:build-info (default) @ kafka-ui-api ---
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.1:install-node-and-pnpm (install node and pnpm) @ kafka-ui-api ---
[INFO] Node v16.15.0 is already installed.
[INFO] PNPM 7.4.0 was installed, but we need version v7.4.0
[INFO] Installing pnpm version v7.4.0
[INFO] Unpacking C:\Users\Franz\.m2\repository\com\github\eirslett\pnpm\7.4.0\pnpm-7.4.0.tar.gz into C:\Users\Franz\Programming\kafka-ui-react-app\node\node_modules
[INFO] Installed pnpm locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.1:pnpm (pnpm install) @ kafka-ui-api ---
[INFO] Running 'pnpm install' in C:\Users\Franz\Programming\kafka-ui-react-app
[INFO] Lockfile is up-to-date, resolution step is skipped
[INFO] Already up-to-date
[INFO] 
[INFO] 
[INFO] --- frontend-maven-plugin:1.12.1:pnpm (pnpm build) @ kafka-ui-api ---
[INFO] Running 'pnpm build' in C:\Users\Franz\Programming\kafka-ui-react-app
[INFO] 
[INFO] > kafka-ui@0.4.0 build C:\Users\Franz\Programming\kafka-ui-react-app
[INFO] > vite build
[INFO] 
[INFO] vite v4.0.0 building for production...
[INFO] transforming...
[INFO] ? 3 modules transformed.
[INFO] [vite]: Rollup failed to resolve import "components/App" from "C:/Users/Franz/Programming/kafka-ui-react-app/src/index.tsx".
[INFO] This is most likely unintended because it can break your application at runtime.
[INFO] If you do want to externalize this module explicitly add it to
[INFO] `build.rollupOptions.external`
[INFO] error during build:
[INFO] Error: [vite]: Rollup failed to resolve import "components/App" from "C:/Users/Franz/Programming/kafka-ui-react-app/src/index.tsx".
[INFO] This is most likely unintended because it can break your application at runtime.
[INFO] If you do want to externalize this module explicitly add it to
[INFO] `build.rollupOptions.external`
[INFO]     at onRollupWarning (file:///C:/Users/Franz/Programming/kafka-ui-react-app/node_modules/.pnpm/vite@4.0.0_binvsr2w2vzqveeue6ibz2djda/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:45707:19)
[INFO]     at onwarn (file:///C:/Users/Franz/Programming/kafka-ui-react-app/node_modules/.pnpm/vite@4.0.0_binvsr2w2vzqveeue6ibz2djda/node_modules/vite/dist/node/chunks/dep-ed9cb113.js:45477:13)
[INFO]     at Object.onwarn (file:///C:/Users/Franz/Programming/kafka-ui-react-app/node_modules/.pnpm/rollup@3.7.3/node_modules/rollup/dist/es/shared/rollup.js:24199:13)
[INFO]     at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/Franz/Programming/kafka-ui-react-app/node_modules/.pnpm/rollup@3.7.3/node_modules/rollup/dist/es/shared/rollup.js:22857:26)
[INFO]     at file:///C:/Users/Franz/Programming/kafka-ui-react-app/node_modules/.pnpm/rollup@3.7.3/node_modules/rollup/dist/es/shared/rollup.js:22818:26
[INFO]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[INFO] ?ELIFECYCLE? Command failed with exit code 1.

I have tried adding `./` in front of `components/App` in the `index.tsx` file. This seems to be solving the issue with `components/App` but then other errors with the same error message but different import appear not solvable by adding `./`. I have also tried implementing [this Stackoverflow answer](https://stackoverflow.com/a/43330003) but without success. 

If anybody has any suggestions how to fix it any help is greatly appreciated.

**Comment by Haarolean** [comment]
@kunzef https://github.com/provectus/kafka-ui/issues/1582

**Comment by credmond** [comment]
@Haarolean I don't think this should have been closed, there's a few problems building on Windows. And I don't actually see why https://github.com/provectus/kafka-ui/issues/1582 is related, or linked to.

We are not (apart from the OP) running the build from the wrong directory.

**Comment by Haarolean** [comment]
> @Haarolean I don't think this should have been closed, there's a few problems building on Windows. And I don't actually see why https://github.com/provectus/kafka-ui/issues/1582 is related, or linked to.
> 
> 
> 
> We are not (apart from the OP) running the build from the wrong directory.

@credmond feel free to raise a new issue
