### ISSUE TITLE
Unable to Edit Setting of a topic from kafka ui getting 404

### ISSUE THREAD

**Issue by nadig-aditya** [provectus/kafka-ui#3554]
**Describe the bug** (Actual behavior)

Getting 404 Error page when i click on Edit setting button for a topic.

**Expected behavior**

We should be allowed to update setting for the topic.
I tried to CLI was able to update the setting for the topic.

**Set up**

1. App version - V0.6.0
2. Helm chart version - 0.6.0

**Steps to Reproduce**

bring up kafka ui and crate a topic and try to edit setting for that topic from ui 
1. 

**Screenshots**

**Additional context**

**Comment by Haarolean** [comment]
Hi,

I'm not able to reproduce the issue, vid attached.
Please attach the similar one with steps to reproduce.

https://user-images.githubusercontent.com/1494347/228045696-0238d4f0-9019-415c-9ba5-1823fb39e756.mov

**Comment by nadig-aditya** [comment]
i observed issue us happening only for Kafka version 2.2.1 (MSK cluster) and not for later versions

**Comment by Haarolean** [comment]
@nadig-aditya can you do a screen record?

**Comment by kaDDDar** [comment]
It looks like its because of message format version: https://github.com/provectus/kafka-ui/blob/master/kafka-ui-react-app/src/lib/constants.ts#L31

My kafka 2.1 cluster uses **message.format.version**: 2.1-IV2
which does not have **max.compaction.lag.ms** described in: https://github.com/provectus/kafka-ui/blob/master/kafka-ui-react-app/src/lib/constants.ts#L33
