### ISSUE TITLE
Blank page for "Reset offsets" when consumer has no committed offsets

### ISSUE THREAD

**Issue by iliax** [provectus/kafka-ui#3932]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

Blank page for "Reset offsets" when consumer has no committed offsets

### Expected behavior

Page is rendered

### Your installation details

[80b748b](https://github.com/provectus/kafka-ui/commit/80b748b)

### Steps to reproduce

1. run consumer group that reads from topic, but does not commit offsets
2. stop CG
3. Consumers -> select created CG -> click "..." -> "Reset offsets" 

### Screenshots

https://github.com/provectus/kafka-ui/assets/702205/027eeb5d-d548-4905-bc0c-fad3626efa1b

**Comment by ksdvishnukumar** [comment]
@iliax , @Haarolean , @freeformz , @stuarth  and @mstolbov  Greetings!!!

I see that this issue is closed but still I see that, when no Active consumer group, i don't see the inactive consumer group in the consumers page. 

I tried with both latest tag image as well as "docker pull provectuslabs/kafka-ui:master"

Both having the same behavior.

Could you please let me know when this feature will be available in the latest tag?
Eagerly waiting for this feature in the UI.


Thankyou...
