### ISSUE TITLE
[feature] In KC UI obfuscate json fields that have "password" in name

### ISSUE THREAD

**Issue by akamensky** [provectus/kafka-ui#980]
### Is your proposal related to a problem?

KC connectors often authentication against relevant source/sink system (i.e. database). Having passwords shown in UI is not secure. Those fields could be obfuscated. This is commonly done by filtering out fields with "password" substring and replacing value with "*****".

### Describe the solution you'd like

Obfuscate JSON of connector before displaying, replacing all fields where key contains "password" substring with "*****".

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by akamensky** [comment]
You are right. Editing is tricky in this case. From my end that's not an issue as we use the UI for viewing and basic operations (editing is done via Git repo code with script to auto-sync it to KC).

In my experience, common approach is that every time the editor would need to enter the password. But in this case each edit modified entire document, which makes this tricky. 

Maybe when editing can check if the line contains "*****" (that is obfuscated field) can show a warning or not allow submission of the form to avoid accidental breaking of the connector.

**Comment by IndeedSi** [comment]
Thanks for the suggestions! I've just got a pr ready for review.
My current changes are more close to what @akamensky describes.  I keep using asterisks because I feel empty string might cause some confusion and asterisks way is how Spring Boot sanitizes.

And the warning banner I added is "Please replace ****** with the real credential values to avoid accidentally breaking your connector config!"

not a native speaker, so any suggestion is welcome🙏
