### ISSUE TITLE
Docker image for arm64

### ISSUE THREAD

**Issue by tigerinus** [provectus/kafka-ui#986]
### Is your proposal related to a problem?

`docker run ...` on ARM64 processor fails.

### Describe the solution you'd like

Please provide Docker image for ARM64

### Describe alternatives you've considered

I can certainly build image myself, but I bet there are people have the same need.

### Additional context

Arm64 based cloud instances are gaining markets. There are Graviton2 from AWS and Ampere from Oracle Cloud, Azure and Tencent Cloud.

**Comment by 5hin0bi** [comment]
Since we are currently using this image as the base one in our docker image: _adoptopenjdk/openjdk13:x86_64-alpine-jre-13.0.2_8_
Our docker image cannot be run on ARM64 architectures even though we build it for linux/amd64 and linux/arm64 platforms in our workflows.

In testing purposes, I've made the next changes in our Dockerfile using the _openjdk:19-slim-bullseye_ image:
![image](https://user-images.githubusercontent.com/94184844/146532546-ad15e159-dae6-43a3-8f9c-6516123e8a06.png)

Built this image as we do in our workflow using docker buildx and tried to start it on my virtual debian buster arm64:
<img width="1777" alt="image" src="https://user-images.githubusercontent.com/94184844/146533613-a2a45177-3c2a-40d5-b5c4-d6afbe6ca444.png">
Feels Goodman!

However, the image size is twice bigger now - 200MB vs. 400MB. We need to decide our further steps: either we accept this size or we do something else to shrink it.

**Comment by 5hin0bi** [comment]
OK. I've managed to run it on Alpine container with additional layer for openjdk 13 installation to shrink the size. Looks to work fine. PR will be created soon.
